### ISSUE TITLE
What does the argument 's_cond' mean?

### ISSUE THREAD

**Issue by JackEasson** [Vchitect/VEnhancer#12]
Thank you so much for open sourcing this amazing work, I want to know the usage of argument of 's_cond', and if it will lead to different results?

**Comment by hejingwenhejingwen** [comment]
's_cond' can be used to control the generative ability, ranging from 1~8.
This checkpoint is not sensitive to 's_cond', it's okay you just fix it to 8.

**Comment by JackEasson** [comment]
Thank you for your reply. Looking forward to seeing more of your great works.
