### ISSUE TITLE
Why my output video of run_VEnhancer.sh is so bad?

### ISSUE THREAD

**Issue by yunkchen** [Vchitect/VEnhancer#13]
https://github.com/user-attachments/assets/02cbf0d9-995a-4ca9-b2e2-915107ad24b9

clip, vae and venhancer models' sha256 has been checked.

**Comment by hejingwenhejingwen** [comment]
Could you please show me your command script?

**Comment by yunkchen** [comment]
> Could you please show me your command script?

`python enhance_a_video.py \
--up_scale 4 --target_fps 24 --noise_aug 250 \
--solver_mode 'fast' --steps 15 \
--input_path prompts/astronaut.mp4 \
--prompt 'An astronaut flying in space, featuring a steady and smooth perspective' \
--save_dir 'results/' \
--model_path venhancer_paper.pt`

**Comment by hejingwenhejingwen** [comment]
> > Could you please show me your command script?
> 
> `python enhance_a_video.py \ --up_scale 4 --target_fps 24 --noise_aug 250 \ --solver_mode 'fast' --steps 15 \ --input_path prompts/astronaut.mp4 \ --prompt 'An astronaut flying in space, featuring a steady and smooth perspective' \ --save_dir 'results/' \ --model_path venhancer_paper.pt`

please check your "model_path". The ckpt may not be loaded.

**Comment by yunkchen** [comment]
> > > Could you please show me your command script?
> > 
> > 
> > `python enhance_a_video.py \ --up_scale 4 --target_fps 24 --noise_aug 250 \ --solver_mode 'fast' --steps 15 \ --input_path prompts/astronaut.mp4 \ --prompt 'An astronaut flying in space, featuring a steady and smooth perspective' \ --save_dir 'results/' \ --model_path venhancer_paper.pt`
> 
> please check your "model_path". The ckpt may not be loaded.

Here is my output log about ckpy loading:

/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
/usr/local/lib/python3.10/dist-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
2024-08-27 17:06:12,445 - video_to_video - INFO - checkpoint_path: venhancer_paper.pt
2024-08-27 17:06:21,383 - video_to_video - INFO - Build encoder with FrozenOpenCLIPEmbedder
/mnt/data/Code/VEnhancer/video_to_video/video_to_video_model.py:35: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  load_dict = torch.load(cfg.model_path, map_location='cpu')
2024-08-27 17:06:37,256 - video_to_video - INFO - Load model path venhancer_paper.pt, with local status <All keys matched successfully>
2024-08-27 17:06:37,257 - video_to_video - INFO - Build diffusion with GaussianDiffusion

**Comment by hejingwenhejingwen** [comment]
If you load the model successfully, you'll see "with local status  All keys matched successfully". 
Please find your model_path, it should be './ckpts/venhancer_paper.pt' if you don't specify it in the command script.

**Comment by yunkchen** [comment]
> If you load the model successfully, you'll see "with local status All keys matched successfully". Please find your model_path, it should be './ckpts/venhancer_paper.pt' if you don't specify it in the command script.

2024-08-27 17:06:37,256 - video_to_video - INFO - Load model path venhancer_paper.pt, with local status \<All keys matched successfully\>
2024-08-27 17:06:37,257 - video_to_video - INFO - Build diffusion with GaussianDiffusion

**Comment by yunkchen** [comment]
’2024-08-27 17:06:37,256 - video_to_video - INFO - Load model path venhancer_paper.pt, with local status <All keys matched successfully>
2024-08-27 17:06:37,257 - video_to_video - INFO - Build diffusion with GaussianDiffusion‘

**Comment by yunkchen** [comment]
Why closed?

**Comment by yunkchen** [comment]
> > If you load the model successfully, you'll see "with local status All keys matched successfully". Please find your model_path, it should be './ckpts/venhancer_paper.pt' if you don't specify it in the command script.
> 
> 2024-08-27 17:06:37,256 - video_to_video - INFO - Load model path venhancer_paper.pt, with local status <All keys matched successfully> 2024-08-27 17:06:37,257 - video_to_video - INFO - Build diffusion with GaussianDiffusion

@hejingwenhejingwen You could find 'All keys matched successfully' in my log.

**Comment by hejingwenhejingwen** [comment]
I have updated my repo several times. Please use the latest version and run it. It should be successful if you install and download models correctly.
