### ISSUE TITLE
timestep gap between I2VGen-XL base model and Enhancer

### ISSUE THREAD

**Issue by ShianDu** [Vchitect/VEnhancer#16]
Congrats on the great work!

I just wonder why there is a timestep gap between I2VGen-XL stage 2 and VEnhancer since the former is 600 while Enhancer uses 900 in base model.

Did VEnhancer just modify this value or use a base model with 900 timestep?

**Comment by hejingwenhejingwen** [comment]
VEnhancer just modifies this value to 900. Actually we are using controlnet, it is supposed to start from pure noise, but empirically 900 obtains more stable performance.

**Comment by ShianDu** [comment]
Thanks for your response!
