### ISSUE TITLE
Can I get some training details?

### ISSUE THREAD

**Issue by lclichen** [Vchitect/VEnhancer#7]
Hi authors,
Thanks for your great work. I'm trying to reproduce the code of the training, so there are a few questions about the details of the training:

1. Is the max_frames fixed during training? Can you share the general setting?
2. The paper mentions adding noise to low-quality frames for enhancement. Is there a similar data enhancement process on gt frames?

By the way, do you have any plans to release the training code? That will be of great help, Thank you again.

**Comment by hejingwenhejingwen** [comment]
- Yes, the max_frames is fixed. 
- For adding noise to the low-quality frames, you can directly use the diffusion process for gt frames, but within a smaller range [0, 300](could be modified up to your needs).

The training code will be released once this work is accepted by one of those popular conferences. Judging from the reviewers' comments, it may take quite a while.

**Comment by lclichen** [comment]
Thank you for your response. I wish you success in getting your paper accepted.

**Comment by lclichen** [comment]
Can you share the init_beta and last_beta values set during training?
